### ISSUE TITLE
[Bug] Sellwand Removes Items with No Remaining Uses

### ISSUE THREAD

**Issue by realdoomsboygaming** [zachfr/SellWand#3]
**Server Version**: Paper 1.21.1 (Latest Release)  
**Plugin**: EconomyShopGUI (Hooked to shop functionality)  
**Issue**: When using a sellwand with no remaining uses on a valid inventory (e.g., a chest with sellable items), all items in the container are still removed, despite the player being notified that the sellwand has no uses left.

---

### Steps to Reproduce:
1. Obtain a sellwand with no remaining uses.
2. Attempt to use it on a chest containing sellable items.
3. The player receives a message stating there are no uses left.
4. Despite the message, all sellable items are removed from the chest's inventory.

---

### Expected Behavior:
When a sellwand has no remaining uses, no items should be removed from any inventory.

### Actual Behavior:
The items are removed even though the sellwand has no remaining uses.

---

### Additional Information:
- **Shop Plugin**: EconomyShopGUI (Default config generation).
- **Configuration**: No custom configurations were made beyond the shop hook.
- **Environment**: Paper 1.21.1, running in a Pterodactyl Linux Docker environment.

**Comment by zachfr** [comment]
Thanks fixed in last version
